spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.initialization-fail-timeout=60000
spring.flyway.url=jdbc:postgresql://ep-shiny-tooth-a2fmhmaa-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.flyway.user=neondb_owner
spring.flyway.password=npg_0lv1aNTiEpuA

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}